# Generated by Django 3.0.6 on 2020-05-25 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InjectionLog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsbrand',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.CreateModel(
            name='UserGS',
            fields=[
                ('brand', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('concentration', models.DecimalField(decimal_places=2, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
