# Generated by Django 3.0.6 on 2020-05-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0002_auto_20200525_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsbrand',
            name='concentration',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='gsbrand',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='injectionlog',
            name='cat_weight',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='injectionlog',
            name='injection_amount',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='usergs',
            name='concentration',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='usergs',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
