# Generated by Django 3.0.6 on 2020-05-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0004_auto_20200525_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='relapse',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cats',
            name='treatment_start',
            field=models.DateField(null=True),
        ),
    ]
