# Generated by Django 3.0.6 on 2020-05-25 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0005_auto_20200525_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='WarriorAdmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InjectionLog.WarriorAdmin'),
        ),
    ]
