# Generated by Django 3.0.6 on 2020-05-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0006_cats_warrioradmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='WarriorAdmin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cats',
            name='relapse',
            field=models.BooleanField(default=False),
        ),
    ]
