# Generated by Django 3.0.6 on 2020-05-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0007_auto_20200525_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
