# Generated by Django 3.0.6 on 2020-05-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0008_cats_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injectionlog',
            name='injection_time',
            field=models.DateTimeField(),
        ),
    ]
