# Generated by Django 3.0.6 on 2020-05-25 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0009_auto_20200525_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='birthday',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cats',
            name='treatment_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='injectionlog',
            name='date_added',
            field=models.DateTimeField(default=datetime.date.today, editable=False),
        ),
    ]
