# Generated by Django 3.0.6 on 2020-05-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0011_auto_20200525_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectionlog',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
