# Generated by Django 3.0.6 on 2020-05-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0013_selectedcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectionlog',
            name='wt_units',
            field=models.CharField(default='lb', max_length=2),
        ),
    ]
