# Generated by Django 3.0.6 on 2020-05-27 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InjectionLog', '0014_injectionlog_wt_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='warrior_admin',
        ),
        migrations.AddField(
            model_name='userextension',
            name='facebook',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userextension',
            name='test_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userextension',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='selectedcat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
