# Generated by Django 3.0.6 on 2020-05-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0016_cats_extended_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='extended_treatment',
            field=models.IntegerField(default=0),
        ),
    ]
