# Generated by Django 3.0.6 on 2020-05-27 15:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InjectionLog', '0017_auto_20200527_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='test_cat',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ObservationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=datetime.date.today, editable=False)),
                ('cat_weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('wt_units', models.CharField(default='lb', max_length=2)),
                ('observation_date', models.DateField(null=True)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=5)),
                ('cat_behavior_today', models.IntegerField(default=3)),
                ('notes', models.TextField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InjectionLog.Cats')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
