# Generated by Django 3.0.6 on 2020-05-28 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0018_auto_20200527_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelapseDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relapse_start', models.DateField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InjectionLog.Cats')),
            ],
        ),
    ]
