# Generated by Django 3.0.6 on 2020-05-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0019_relapsedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='relapsedate',
            name='neuro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relapsedate',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='relapsedate',
            name='ocular',
            field=models.BooleanField(default=False),
        ),
    ]
