# Generated by Django 3.0.6 on 2020-05-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0020_auto_20200528_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationlog',
            name='temp_units',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
