# Generated by Django 3.0.6 on 2020-05-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0021_observationlog_temp_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationlog',
            name='cat_weight',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='observationlog',
            name='temp_units',
            field=models.CharField(default='F', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='observationlog',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='observationlog',
            name='wt_units',
            field=models.CharField(default='lb', max_length=2, null=True),
        ),
    ]
