# Generated by Django 3.0.6 on 2020-05-29 23:54

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0022_auto_20200529_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodWork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bloodname', models.CharField(max_length=200)),
                ('map_data', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='FIPlog/')),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InjectionLog.Cats')),
            ],
        ),
    ]
