# Generated by Django 3.0.6 on 2020-05-30 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0023_bloodwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodwork',
            name='map_data',
        ),
        migrations.AddField(
            model_name='bloodwork',
            name='bloodwork_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bloodwork',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bloodwork',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
