# Generated by Django 3.0.6 on 2020-05-30 04:57

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0024_auto_20200530_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodwork',
            name='bloodwork',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='FIPlog/'),
        ),
        migrations.AlterField(
            model_name='bloodwork',
            name='cat_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InjectionLog.Cats'),
        ),
    ]
