# Generated by Django 3.0.6 on 2020-05-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0025_auto_20200530_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodwork',
            name='bloodwork',
            field=models.FileField(null=True, upload_to='FIPlog/'),
        ),
    ]
