# Generated by Django 3.0.6 on 2020-05-31 17:36

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0026_auto_20200531_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodwork',
            name='bloodwork',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='FIPlog/'),
        ),
    ]
