# Generated by Django 3.0.6 on 2020-05-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0027_auto_20200531_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodwork',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bloodwork',
            name='url_link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
