# Generated by Django 3.0.6 on 2020-05-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0028_auto_20200531_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodwork',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodwork',
            name='url_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
