# Generated by Django 3.0.6 on 2020-05-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0029_auto_20200531_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='sharable',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
