# Generated by Django 3.0.6 on 2020-06-21 23:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0031_warriortracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='relapsedate',
            name='fip_type',
            field=models.CharField(default='dry', max_length=32),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BloodSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt_date', models.DateField(default=datetime.date.today)),
                ('rbc', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('hct', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('hgb', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('wbc', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('pct_lym', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('pct_neu', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('lym', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('neu', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('tp', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('alb', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('glob', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('a_g', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('tbil', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InjectionLog.Cats')),
            ],
        ),
    ]
