# Generated by Django 3.0.6 on 2020-07-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0032_auto_20200621_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectionlog',
            name='new_symptom',
            field=models.TextField(null=True),
        ),
    ]
