# Generated by Django 3.0.6 on 2020-07-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0033_injectionlog_new_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='cured',
            field=models.BooleanField(default=False),
        ),
    ]
