# Generated by Django 3.0.6 on 2020-07-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0034_cats_cured'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsbrand',
            name='admin_method',
            field=models.CharField(default='Injectable', max_length=10),
        ),
        migrations.AddField(
            model_name='usergs',
            name='admin_method',
            field=models.CharField(default='Injectable', max_length=10),
        ),
    ]
