# Generated by Django 3.0.6 on 2021-12-06 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionLog', '0040_cats_bad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_3', models.BooleanField(default=False)),
                ('day_77', models.BooleanField(default=False)),
                ('day_30', models.BooleanField(default=False)),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InjectionLog.Cats')),
            ],
        ),
    ]
